News/urls.py
from django.conf.urls import url,include

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static

from django.conf import settings

from main.views import PermissionDenied

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    url(r'^', include('main.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^permission-denied', PermissionDenied.as_view(), name='permission-denied'),
    url(r'^api/v1/main/', include('main.api.urls'), name="api-root"),
    url(r'^api/v1/user/', include('user.api_v1.urls', namespace='user-v1')),
    url('api/v1/rest-auth/', include('rest_auth.urls')),
    url('api/v1/rest-auth/registration/', include('rest_auth.registration.urls')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/api_v1/urls.py
from __future__ import unicode_literals
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from rest_framework import routers

from user.api_v1 import api

router = routers.SimpleRouter()

urlpatterns = [
    # urls for Django Rest Framework API
    url(r'^profile/$', csrf_exempt(api.UserViewSet.as_view()), name='user-detail')

]

user/urls.py
from django.conf.urls import url
from user import views

from main.helper import anonymous_required
from django.contrib.auth.decorators import login_required

# TEMPLATE TAGGING
app_name = 'user'

urlpatterns = (
    url('^login', anonymous_required(views.UserLogin.as_view()), name='user_login'),
    url('^logout', views.user_logout, name='user_logout'),
    url(r'^register/$', anonymous_required(views.UserRegister.as_view()), name='user_register'),
    url(r'^profile/$', login_required(views.ProfileDetailView.as_view()), name='profile'),
    url(r'^profile/update/$', login_required(views.ProfileUpdateView.as_view()), name='update_profile'),
    url(r'^change_password/$', login_required(views.ChangePassword.as_view()), name='change_password'),
    url(r'^password_reset/$', views.PasswordReset.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDone.as_view(), name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

)

user/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm

from user.utils import normalise_email, get_user_permission
from user.models import User


from user.models import Task


class UpdateProfileForm(forms.ModelForm):
    phone_number = forms.RegexField(required=False, regex=r'^\d{9,15}$', max_length=15,
                                    help_text=_("In case we need to contact you"),
                                    widget=forms.TextInput(
                                        attrs={'class': 'form-control', 'placeholder': _("Phone Number")}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'gender', 'phone_number', 'address',)
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('First Name')}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Last Name')}),
            # 'phone_number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone number'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Address')}),
        }

    def __init__(self, user, *args, **kwargs):
        try:
            instance = User.objects.get(pk=user.pk)
        except User.DoesNotExist:
            # User has no profile, try a blank one
            instance = User(user=user)
        kwargs['instance'] = instance

        super(UpdateProfileForm, self).__init__(*args, **kwargs)
        self.fields['gender'].widget.attrs['class'] = 'form-control'

    def save(self, *args, **kwargs):
        user = self.instance

        # Save user also
        for field_name in self.fields:
            setattr(user, field_name, self.cleaned_data[field_name])
        user.save()

        return super(UpdateProfileForm, self).save(*args, **kwargs)


class LoginForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('email', 'password')

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': _('Email address')}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': _('Password')}),
        }


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': _('Email address')}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'form-control', 'placeholder': _('Password')})
        self.fields['password2'].widget.attrs.update({'class': 'form-control', 'placeholder': _('Confirm Password')})

    def clean_email(self):
        email = normalise_email(self.cleaned_data["email"])
        if User._default_manager.filter(email__iexact=email).exists():
            raise forms.ValidationError(_("A user with that email address already exists"))
        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.username = user.email = self.cleaned_data["email"]
        user.password1 = self.cleaned_data["password1"]
        user.password2 = self.cleaned_data["password2"]
        if commit:
            user.save()
        return user


class ChangePasswordForm(UserCreationForm, forms.Form):
    old_password_flag = True  # Used to raise the validation error when it is set to False
    old_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('old_password', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({'class': 'form-control', 'placeholder': _('New Password')})
        self.fields['password2'].widget.attrs.update({'class': 'form-control', 'placeholder': _('Confirm Password')})
        self.fields['old_password'].widget.attrs.update({'class': 'form-control', 'placeholder': _('Old Password')})

    def set_old_password_flag(self):

        self.old_password_flag = False

        return 0

    def clean_old_password(self, *args, **kwargs):
        old_password = self.cleaned_data.get('old_password')

        if not old_password:
            raise forms.ValidationError(_("You must enter your old password."))

        if not self.old_password_flag:
            raise forms.ValidationError(_("The old password that you have entered is wrong."))

        return old_password


# def get_website_choices():
#     result = CrawlerApi('crawling')
#     data = result.sites_info(False)
#     final_data = []
#     for val in data:
#         if 'key' in val:
#             final_data.append((val['key'], val['logo']))
#     return final_data
#
#
# class CreateTaskForm(forms.ModelForm):
#     action_type = forms.ChoiceField(widget=forms.RadioSelect())
#     website = forms.MultipleChoiceField(choices=get_website_choices(), widget=PrettyCheckboxWidget())
#
#     class Meta:
#         model = Task
#         fields = ('search_term', 'action_type', 'website')
#
#     def __init__(self, user, *args, **kwargs):
#         super(CreateTaskForm, self).__init__(*args, **kwargs)
#         user_permission = get_user_permission(user)
#
#         if user_permission:
#             if user_permission in [1, 2, 3]:
#                 self.fields['action_type'].choices = [
#                     ('CS', _('Crawler with schedule'))]
#                 self.fields['action_type'].initial = 'CS'
#                 self.fields['action_type'].widget = forms.HiddenInput()
#             # if user_permission == 3:
#             #     self.fields['action_type'].choices = [
#             #         ('CW', _('Crawler without schedule'))]
#
#         self.fields['search_term'].widget.attrs.update(
#             {'class': 'form-control', 'placeholder': _('What are you looking for')})
#
#     def save(self, user, user_ip, commit=True):
#         task = super(CreateTaskForm, self).save(commit=False)
#         task.user = user
#         task.ip_address = user_ip
#         task.status = 0
#         if commit:
#             task.save()
#         return task


class CustomPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': _('Enter your email...')})

    def clean_email(self):
        email = normalise_email(self.cleaned_data["email"])
        if not User._default_manager.filter(email__iexact=email).exists():
            raise forms.ValidationError(_("Email Not Registred"))
        return email


class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': _('New Password')})
        self.fields['new_password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': _('Confirm Password')})

user/views.py
from django.contrib.auth import authenticate, login, logout

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

from django.shortcuts import render
from django.contrib.auth import update_session_auth_hash

from user.forms import User, LoginForm, RegisterForm, UpdateProfileForm, ChangePasswordForm, CustomPasswordResetForm, \
    CustomSetPasswordForm

from django.views.generic import TemplateView, FormView, CreateView
from django.urls import reverse_lazy
from django.shortcuts import redirect

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from django.utils.translation import ugettext_lazy as _
from django.utils.translation import get_language

from user.utils import get_user_ip, CustomView, get_user_permission


class UserLogin(FormView):
    template_name = 'login.html'
    form_class = LoginForm

    # success_url = '/login/'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = authenticate(username=form.cleaned_data.get('email'), password=form.cleaned_data.get('password'))

            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            else:
                messages.error(request, _("Please enter a correct email address and password."))
                return render(request, self.template_name, {'form': form})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


class UserRegister(FormView):
    template_name = 'register.html'
    form_class = RegisterForm

    # success_url = '/login/'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save()
            user.set_password(user.password1)
            user.save()

            # after the user is registered go to login page
            # return HttpResponseRedirect(reverse('user:user_login'))
            user = authenticate(username=form.cleaned_data.get('email'), password=form.cleaned_data.get('password1'))
            if user and user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))

        return render(request, self.template_name, {'form': form})


class ProfileDetailView(TemplateView):
    template_name = "user_profile.html"

    def get_context_data(self, **kwargs):
        ctx = super(ProfileDetailView, self).get_context_data(**kwargs)
        ctx['user'] = self.request.user
        return ctx

    def get_object(self):
        return self.request.user


class ProfileUpdateView(FormView):
    form_class = UpdateProfileForm
    template_name = "update_profile.html"
    success_url = reverse_lazy('user:profile')

    def get_form_kwargs(self):
        kwargs = super(ProfileUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        # Grab current user instance before we save form.  We may need this to
        # send a warning email if the email address is changed.
        try:
            old_user = User.objects.get(id=self.request.user.id)
        except User.DoesNotExist:
            old_user = None

        form.save()
        messages.success(self.request, _("Profile updated"))
        return redirect(self.get_success_url())


class ChangePassword(FormView):
    form_class = ChangePasswordForm
    template_name = 'change_user_password.html'
    success_url = reverse_lazy('user:profile')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        try:
            old_user = User.objects.get(id=self.request.user.id)
            if old_user.check_password(form.data.get("old_password")) == False:
                form.set_old_password_flag()

            if form.is_valid():
                old_user.set_password(form.data.get("password1"))
                old_user.save()
                update_session_auth_hash(self.request, old_user)

                messages.success(self.request, _("Password Changed Successfully"))
                return redirect(self.get_success_url())
            else:
                return render(request, self.template_name, {'form': form})
        except User.DoesNotExist:
            old_user = None


# class CreateTask(CreateView, CustomView):
#     template_name = "create_task.html"
#     form_class = CreateTaskForm
#     success_url = reverse_lazy('user:create_task')
#     custom_permissions = ['only_logged_in', 'user_permission']
#
#     def user_permission(self, request, *args, **kwargs):
#         user_login = request.user
#         user = get_user_permission(user_login)
#         if user:
#             if user in [1, 2, 3]:
#                 return True
#         else:
#             return redirect(reverse('permission-denied'))
#
#     def get_form_kwargs(self):
#         kwargs = super(CreateTask, self).get_form_kwargs()
#         kwargs['user'] = self.request.user
#         return kwargs
#
#     def form_valid(self, form):
#         search_term = form.cleaned_data.get('search_term')
#         website = form.cleaned_data.get('website')
#         action_type = form.cleaned_data.get('action_type')
#         try:
#             result = CrawlerApi('crawling')
#             result.create_task(search_term=search_term, action_type=action_type, websites=website)
#             if self.request.user:
#                 user_ip = get_user_ip(self.request)
#                 self.object = form.save(self.request.user, user_ip)
#         except:
#             messages.info(self.request, "Something is wrong check your data")
#             return super(CreateTask, self).form_invalid(form)
#
#         messages.info(self.request, _("Your results will be available soon."))
#         return redirect(self.get_success_url())


class PasswordReset(PasswordResetView, CustomView):
    template_name = 'password_reset_form.html'
    email_template_name = 'password_reset_email.html'
    success_url = reverse_lazy('user:password_reset_done')
    form_class = CustomPasswordResetForm
    custom_permissions = ['only_not_logged_in']

    def __init__(self, *args, **kwargs):
        super(PasswordReset, self).__init__(*args, **kwargs)
        if get_language() == 'ar':
            self.email_template_name = "password_reset_email_ar.html"


class PasswordResetDone(PasswordResetDoneView, CustomView):
    template_name = 'password_reset_done.html'
    custom_permissions = ['only_not_logged_in']


class PasswordResetConfirm(PasswordResetConfirmView, CustomView):
    template_name = 'password_reset_confirm.html'
    success_url = reverse_lazy('user:password_reset_complete')
    form_class = CustomSetPasswordForm
    custom_permissions = ['only_not_logged_in']


class PasswordResetComplete(PasswordResetCompleteView, CustomView):
    template_name = 'password_reset_complete.html'
    custom_permissions = ['only_not_logged_in']

user/templates/change_user_password.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container result-container bg-white border">
        <div class="row">
            <div class="col-12">
                <div class="row text-center">
                    <div class="col-12">
                        <div class="thumbnail ">
                            <img src="{% static 'img/noimg_profile.png' %}">
                        </div>
                        <div class="col-sm-12 pt-2">
                            {% if user.first_name %}
                                {{ user.get_full_name|default:'-' }}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <form class="change-password-form" method="POST">
                    {% csrf_token %}
                    <div class="row pt-5">
                        <div class="col-3 bold">{% trans "Old Password" %}</div>
                        <div class=" col-8">
                            {% include "main/form_field.html" with field=form.old_password %}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-3 bold">{% trans "New Password" %}</div>
                        <div class=" col-8">
                             {% include "main/form_field.html" with field=form.password1 help_text=False %}
                        </div>
                    </div>
                    <hr>
                    <div class="row pb-3">
                        <div class="col-3 bold">{% trans "Confirm Password" %}</div>
                        <div class=" col-8">
                             {% include "main/form_field.html" with field=form.password2 help_text=False %}
                        </div>
                    </div>
                    <div class="row text-center pb-3">
                        <div class="col-3 bold"></div>
                        <div class="col-md-3 col-sm-8 col-md-offset-6 col-sm-offset-4 col-xs-6">
                            <button type="submit"
                                    class="btn btn-block btn-primary  btn-font-fff-bold"
                                    data-loading-text="{% trans "Saving..." %}">{% trans "Save" %}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/create_task.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="registration-forms-container bg-white border">
            <h3 class="text-center">{% trans "Create Task" %}</h3>
            {% include "main/messages.html" %}
            <form method="POST" class="create_task_form">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 pt-3">{% include 'main/form_field.html' with field=form.search_term %} </div>
                    <div class="col-12 pt-3">{% include 'main/form_field.html' with field=form.website %}</div>
                    <div class="col-12 ">{% include 'main/form_field.html' with field=form.action_type %}</div>
                    <div class="col-12">
                        <input type="submit" class="btn btn-success btn-block font-weight-bold"
                               value="{% trans "Create Task" %}">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

user/templates/login.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="registration-forms-container bg-white text-center border">
        <img class="mw-100" src="{% if LANGUAGE_CODE == "en" %}{% static "img/news-en-logo.png" %}{% else %}{% static "img/news-ar-logo.png" %}{% endif %}">
            {% include "main/messages.html" %}
            <form method="POST" action="{% url 'user:user_login' %}" class="login-form">
                {% csrf_token %}
                <div class="form-group pt-3">{% include 'main/form_field.html' with field=form.email %} </div>
                <div class="form-group">{% include 'main/form_field.html' with field=form.password %}</div>
                <input type="submit" class="btn btn-danger btn-block font-weight-bold" value="{% trans "Login" %}">
                <button class="btn btn-link" onclick="location.href='{% url 'user:password_reset' %}';" type="button">
                    {% trans "Forgot Your Password?" %}
                </button>
            </form>

            <p>{% trans "You Dont Have An Account?" %}</p>
            <a href="{% url 'user:user_register' %}" class="btn btn-secondary col-6">{% trans "Register Now" %}</a>
        </div>
    </div>
{% endblock %}

user/templates/password_reset_complete.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="registration-forms-container bg-white text-center border">
            <p>
                {% trans "Your password has been set. You may go ahead and " %}<a href="{% url 'user:user_login' %}"
            >{% trans "Login" %}</a>
                {% trans "now." %}
            </p>
        </div>
    </div>
{% endblock %}

user/templates/password_reset_confirm.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="registration-forms-container border bg-white border">
            {% if validlink %}
                <h3 class="text-center">{% trans "Create New Password" %}</h3>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group pt-3">{% include 'main/form_field.html' with field=form.new_password1 help_text=False %}</div>
                    <div class="form-group">{% include 'main/form_field.html' with field=form.new_password2 help_text=False %}</div>
                    <input type="submit" value="{% trans "Change password" %}" class="btn btn-success btn-block">
                </form>
            {% else %}
                <p>
                    {% trans "The password reset link has expired, because it has already been used. Please request a new password reset." %}
                </p>

            {% endif %}
        </div>
    </div>
{% endblock %}

user/templates/password_reset_done.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="registration-forms-container bg-white border">
            <p>
                {% trans "* We've emailed you instructions for setting your password. If an account exists with the email you entered. You should receive them shortly." %}
            </p>
            <p>
                {% trans "* If you don't receive an email, please make sure you've entered the email you registered with, and check your spam folder." %}
            </p>
        </div>
    </div>
{% endblock %}

user/templates/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} Prizila Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
Prizila Team
{% endautoescape %}

user/templates/password_reset_email_ar.html
{% autoescape off %}
 على نيوز{{ user.get_username }}  ,للبدء بعملية اعادة ضبط كلمة السر الخاصة بحسابك
اضغط على الرابط أسفله:

{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

إذا كان الضغط على الرابط أعلاه لا يعمل, الرجاء نسخ و لصق الرابط في صفحة متصفح جديدة

تحيات,
فريق عمل نيوز
{% endautoescape %}

user/templates/password_reset_form.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="registration-forms-container bg-white text-center border">
            <h3>{% trans "Forgot Your Password?" %}</h3>
            <p>{% trans "Enter the e-mail address associated with your account. Click submit to have your password e-mailed to you." %}</p>
            {% include "main/messages.html" %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">{% include 'main/form_field.html' with field=form.email %}</div>
                <input type="submit" class="btn btn-success btn-block font-weight-bold"
                       value="{% trans "Send Reset Email" %}">
            </form>
        </div>
    </div>
{% endblock %}

user/templates/register.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container">
        <div class="registration-forms-container bg-white text-center border">
        <img class="mw-100" src="{% if LANGUAGE_CODE == "en" %}{% static "img/news-en-logo.png" %}{% else %}{% static "img/news-ar-logo.png" %}{% endif %}">
            {% include "main/messages.html" %}
            <form method="POST" action="{% url 'user:user_register' %}" class="register-form pt-3">
                {% csrf_token %}
                <div class="form-group">{% include 'main/form_field.html' with field=form.email %} </div>
                <div class="form-group">{% include 'main/form_field.html' with field=form.password1 %}</div>
                <div class="form-group">{% include 'main/form_field.html' with field=form.password2 %}</div>
                <input type="submit" class="btn btn-danger btn-block font-weight-bold" value="Register">
                <p class="text-center font-weight-bold pt-3">{% trans "Already have an account?" %}</p>
                <a href="{% url 'user:user_login' %}" class="btn btn-secondary col-4 font-weight-bold">{% trans "Login" %}</a>

            </form>
        </div>
    </div>
{% endblock %}

user/templates/user_profile.html
{% extends "main/layout/layout.html" %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
    <div class="container result-container bg-white border">
        <div class="row">
            <div class="col-12">
                <div class="row text-center">
                    <div class="col-12">
                        <div class="thumbnail ">
                            <img src="{% static '/img/noimg_profile.png' %}">
                        </div>
                        <div class="col-sm-12 pt-2">
                            {% if user.first_name %}
                                {{ user.get_full_name|default:'-' }}
                            {% else %}
                                {{ user.email|default:'-' }}
                            {% endif %}
                        </div>

                        <div class="col-md-12">
                            <a href="{% url 'user:update_profile' %}"
                               class="btn btn-link">{% trans "Edit Info" %}</a> |
                            <a href="{% url 'user:change_password' %}"
                               class="btn btn-link">{% trans "Change password" %}</a>
                        </div>
                    </div>
                    {% include "main/messages.html" %}
                </div>
                <div class="row pt-3">
                    <div class="col-3 bold">{% trans "Email Address" %}</div>
                    <div class=" col-8">
                        {{ user.email }}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-3 bold">{% trans "Full name" %}</div>
                    <div class=" col-8">
                        {% if user.first_name or user.last_name %}
                            {{ user.get_full_name }}
                        {% else %}
                            -
                        {% endif %}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-3 bold">{% trans "Gender" %}</div>
                    <div class=" col-8">
                        {% if user.gender %}
                            {{ user.get_gender_display }}
                        {% else %}
                            Not specified
                        {% endif %}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-3 bold">{% trans "Phone Number" %}</div>
                    <div class=" col-8">
                        {% if user.phone_number %}
                            {{ user.phone_number }}
                        {% else %}
                            -
                        {% endif %}
                    </div>
                </div>
                <hr>
                <div class="row pb-3">
                    <div class="col-3 bold">{% trans "Address" %}</div>
                    <div class=" col-8">
                        {% if user.address %}
                            {{ user.address }}
                        {% else %}
                            -
                        {% endif %}
                    </div>
                </div>
{#                {% if request.user.is_superuser or request.user.is_staff or request.user.is_user_paid %}#}
{#                    <div class="row text-center">#}
{#                        <div class="col-3 bold"></div>#}
{#                        <div class="col-md-3 pb-3 pt-2 col-sm-8 col-md-offset-6 col-sm-offset-4 col-xs-6">#}
{#                            <a href="{% url 'user:create_task' %}"#}
{#                               class=" btn btn-block btn-primary btn-font-fff-bold"#}
{#                               data-loading-text="{% trans "Saving..." %}">{% trans "Create New Task" %}#}
{#                            </a>#}
{#                        </div>#}
{#                    </div>#}
{#                {% endif %}#}
            </div>
        </div>
    </div>
{% endblock %}