News/urls.py
from django.conf.urls import url,include

from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf.urls.static import static

from django.conf import settings

from main.views import PermissionDenied

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    url(r'^', include('main.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^permission-denied', PermissionDenied.as_view(), name='permission-denied'),
    url(r'^api/v1/main/', include('main.api.urls'), name="api-root"),
    url(r'^api/v1/user/', include('user.api_v1.urls', namespace='user-v1')),
    url('api/v1/rest-auth/', include('rest_auth.urls')),
    url('api/v1/rest-auth/registration/', include('rest_auth.registration.urls')),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/api/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from main.api import views

router = routers.DefaultRouter()
router.register(r'websitesInfo', views.WebSiteViewSet, base_name='websitesinfo')
router.register(r'websites', views.NewsWebSiteViewSet, base_name='newswebsite')
router.register(r'news', views.NewsViewSet)
router.register(r'last_news', views.LastNewsViewSet, base_name='last_news')

urlpatterns = [
    # urls for Django Rest Framework API
    url('^', include(router.urls)),
]

main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^search', views.SerchForm.as_view(), name="search_news"),
    url(r'^news/list/(?P<pk>\d+)$', views.NewsListView.as_view(), name="news_list"),
    url(r'^news/detail/(?P<pk>\d+)$', views.NewsDetailView.as_view(), name='news_detail')
]

user/urls.py
from django.conf.urls import url
from user import views

from main.helper import anonymous_required
from django.contrib.auth.decorators import login_required

# TEMPLATE TAGGING
app_name = 'user'

urlpatterns = (
    url('^login', anonymous_required(views.UserLogin.as_view()), name='user_login'),
    url('^logout', views.user_logout, name='user_logout'),
    url(r'^register/$', anonymous_required(views.UserRegister.as_view()), name='user_register'),
    url(r'^profile/$', login_required(views.ProfileDetailView.as_view()), name='profile'),
    url(r'^profile/update/$', login_required(views.ProfileUpdateView.as_view()), name='update_profile'),
    url(r'^change_password/$', login_required(views.ChangePassword.as_view()), name='change_password'),
    url(r'^password_reset/$', views.PasswordReset.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', views.PasswordResetDone.as_view(), name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

)

main/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from dynamic_scraper.models import Scraper, SchedulerRuntime
from scrapy_djangoitem import DjangoItem
from django.utils.translation import ugettext_lazy as _


class WebsiteInfo(models.Model):
    LANGUAGE_CHOICES = (
        ('ar', _('Arabic')),
        ('en', _('English')),
    )
    key = models.CharField(max_length=30)
    website_type = models.CharField(max_length=2, blank=True, null=True, choices=LANGUAGE_CHOICES)
    search_domain = models.CharField(max_length=200)
    scraper = models.ForeignKey(Scraper, blank=True, null=True, on_delete=models.SET_NULL)
    image = models.ImageField(max_length=256, upload_to='website_pics')

    def __str__(self):
        return self.key


class NewsWebsite(models.Model):
    LANGUAGE_CHOICES = (
        ('ar', _('Arabic')),
        ('en', _('English')),
    )
    name = models.CharField(max_length=200)
    url = models.URLField()
    scraper = models.ForeignKey(Scraper, blank=True, null=True, on_delete=models.SET_NULL)
    scraper_runtime = models.ForeignKey(SchedulerRuntime, blank=True, null=True, on_delete=models.SET_NULL)
    language = models.CharField(max_length=2, blank=True, null=True, choices=LANGUAGE_CHOICES)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class News(models.Model):
    title = models.CharField(max_length=200)
    news_website = models.ForeignKey(NewsWebsite)
    description = models.TextField(blank=True)
    image = models.URLField()
    url = models.URLField()
    item_website = models.CharField(max_length=200, null=True, blank=True)
    checker_runtime = models.ForeignKey(SchedulerRuntime, blank=True, null=True, on_delete=models.SET_NULL)
    created_date = models.DateTimeField(null=True, blank=True)

    def __unicode__(self):
        return self.title

    # def save(self, *args, **kwargs):
    #     from bs4 import BeautifulSoup
    #     import json
    #     table_data = [[cell.text for cell in row("td")]
    #                   for row in BeautifulSoup(self.description)("tr")]
    #     self.djson = json.dumps(dict(table_data))
    #     # from crawling.Html2Json import html_to_json
    #     # self.djson = html_to_json(self.description)
    #     super(Product, self).save(*args, **kwargs)

    # def djson_formatted(self):
    #     from django.utils.safestring import mark_safe
    #
    #     data = json.loads(self.djson, encoding='utf-8')
    #
    #     return mark_safe(data)
    #
    #     djson_formatted.short_description = 'Details Formatted'


class NewsItem(DjangoItem):
    django_model = News


@receiver(pre_delete)
def pre_delete_handler(sender, instance, using, **kwargs):
    if isinstance(instance, News):
        if instance.checker_runtime:
            instance.checker_runtime.delete()


pre_delete.connect(pre_delete_handler)

main/api/views.py
from rest_framework import viewsets, filters
from rest_framework.response import Response
from django.db.models import Q
from main.api.serializers import WebSiteInfoSerializer, NewsSerializer, NewsDetailsSerializer, NewsWebsiteSerializer
from main.models import WebsiteInfo, News, NewsWebsite
from main.utils import get_news_distinct
from main.views import single_crawl_without_scheduling_celery

from django.utils.translation import get_language


class WebSiteViewSet(viewsets.ModelViewSet):
    """from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
    API endpoint that allows users to be viewed or edited.
    """
    queryset = WebsiteInfo.objects.all()
    serializer_class = WebSiteInfoSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ('key', 'url',)

    def get_queryset(self):
        q = super(WebSiteViewSet, self).get_queryset()
        if get_language() == 'ar':
            return q.filter(website_type=get_language())
        else:
            return q.filter(website_type=get_language())


class NewsWebSiteViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = NewsWebsite.objects.all()
    serializer_class = NewsWebsiteSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ('name', 'url',)


class LastNewsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    serializer_class = NewsSerializer
    filter_backends = (filters.SearchFilter,)
    details_serializer_class = NewsDetailsSerializer

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        kwargs['context'] = self.get_serializer_context()
        serializer = self.details_serializer_class(instance, context={'request': request})
        return Response(serializer.data)

    def get_queryset(self):
        data = get_news_distinct()
        return data


class NewsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = News.objects.all().order_by('-created_date')
    serializer_class = NewsSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ('title', 'description',)

    details_serializer_class = NewsDetailsSerializer

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        kwargs['context'] = self.get_serializer_context()
        serializer = self.details_serializer_class(instance, context={'request': request})
        return Response(serializer.data)

    def filter_queryset(self, queryset):
        if 'pk' in self.kwargs:
            filtered_queryset = super(NewsViewSet, self).filter_queryset(queryset)
            return filtered_queryset.filter(pk=self.kwargs['pk'])

        websiteInfo_id = self.request._request.GET.get("websiteinfo_id", "")
        if websiteInfo_id:
            website = WebsiteInfo.objects.get(id=websiteInfo_id)
            filtered_queryset = super(NewsViewSet, self).filter_queryset(queryset)
            return filtered_queryset.filter(news_website__name__contains=website.key)

        search_term = self.request._request.GET.get("search", "").strip()
        if not search_term:
            filtered_queryset = super(NewsViewSet, self).filter_queryset(queryset)
            return filtered_queryset
        if not self.request._request.GET.getlist("websites"):
            website_info_qs = WebsiteInfo.objects.all()
        else:
            website_info_qs = WebsiteInfo.objects.filter(
                key__in=self.request._request.GET.getlist("websites"))
        if not website_info_qs:
            return []
        website_list = list(each_website.key for each_website in website_info_qs)
        if self.request.GET.get("action_type") in ["DB", "CS", "CW"]:

            result = single_crawl_without_scheduling_celery(search_term, website_list,
                                                            self.request.GET.get("action_type"))
            if not result:
                return []
        filtered_queryset = super(NewsViewSet, self).filter_queryset(queryset)
        return filtered_queryset.filter(Q(item_website__in=website_list))

main/views.py
from main.tasks import single_crawl_without_scheduling
from django.http import Http404

from django.contrib import messages

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

from django.views.generic import TemplateView, ListView, DetailView

from main.models import News, WebsiteInfo
from random import sample

# Create your views here.
from main.utils import get_news_distinct


class Home(TemplateView):
    home = True
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['home'] = self.home
        # count = News.objects.all().count()
        # rand_ids = sample(range(1, count), 10)
        # context['news_list'] = News.objects.filter(id__in=rand_ids).distinct()
        context['news_list'] = get_news_distinct()
        return context


class NewsListView(ListView):
    model = News
    template_name = 'main/news_list.html'
    news_list = True

    def get_queryset(self, **kwargs):
        try:
            website = WebsiteInfo.objects.get(pk=self.kwargs['pk'])
            return News.objects.filter(news_website__name__contains=website.key).order_by('-created_date')
        except:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(NewsListView, self).get_context_data(**kwargs)
        context['news_list_view'] = self.news_list
        return context


class NewsDetailView(DetailView):
    template_name = 'main/news_detail.html'
    model = News
    context_object_name = 'news_detail'


class SerchForm(TemplateView):

    def get(self, request, *args, **kwargs):
        text = request.GET['search_text']
        websites_list = request.GET.getlist('check')
        if text:
            if websites_list:
                data_news = []
                for website in websites_list:
                    data_news += News.objects.filter(title__icontains=text, description__icontains=text,
                                                     news_website__name__icontains=website)
                if data_news:
                    return render(request, 'main/news_list.html', {'news_list': data_news})
                else:
                    there_have_news = single_crawl_without_scheduling.apply_async(args=[text, websites_list])
                    if there_have_news.get()[0]:
                        for website in websites_list:
                            website_news_name = website + "_" + text.replace(" ", "_")
                            data_news += News.objects.filter(title__icontains=text, description__icontains=text,
                                                             news_website__name=website_news_name)
                    return render(request, 'main/news_list.html', {'news_list': data_news})
            else:
                data_news = News.objects.filter(title__icontains=text, description__icontains=text, )
                if data_news:
                    return render(request, 'main/news_list.html', {'news_list': data_news})
                else:
                    return render(request, 'main/news_list.html', {})

        else:
            messages.error(request, "Invalid Text, please try again!")
            return redirect(reverse('home'))


class PermissionDenied(TemplateView):
    template_name = 'main/403.html'


def single_crawl_without_scheduling_celery(search_term, websites_keys, scheduled=True):
    result = single_crawl_without_scheduling.apply_async(args=[search_term, websites_keys, scheduled])
    return result.get()[0]

main/templates/layout/tools/footer.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!-- Footer -->
<footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="footer_content col-lg-6 h-100 text-center{% if LANGUAGE_CODE == 'ar' %} text-lg-right{% else %} text-lg-left{% endif %} my-auto">
                <ul class="list-inline  mb-2">
                    <li class="list-inline-item">
                        <a href="#">{% trans "About" %}</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">{% trans "Contact" %}</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">{% trans "Terms of Use" %}</a>
                    </li>
                    <li class="list-inline-item">&sdot;</li>
                    <li class="list-inline-item">
                        <a href="#">{% trans "Privacy Policy" %}</a>
                    </li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">{% trans "&copy; Your Website 2018. All Rights Reserved." %}</p>
            </div>
            <div class="col-lg-6 h-100 text-center{% if LANGUAGE_CODE == 'ar' %} text-lg-left{% else %} text-lg-right{% endif %} my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fa fa-facebook fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="#">
                            <i class="fa fa-twitter fa-2x fa-fw"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <i class="fa fa-instagram fa-2x fa-fw"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

main/templates/layout/tools/header.html
{% load i18n %}
{% load staticfiles %}
{% get_current_language as LANGUAGE_CODE %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" canvas="header">
    <button class="js-toggle-slidebar toggler"
            type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand pl-3" href="{% url 'home' %}">
        <img class="mainlogo" src="{% if LANGUAGE_CODE == "en" %}{% static "img/news-en-logo.png" %}{% else %}{% static "img/news-ar-logo.png" %}{% endif %}">
    </a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">

        {% include "layout/tools/main_menu.html" %}
    </div>
</nav>

main/templates/layout/tools/main_menu.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{#<ul class="navbar-nav{% if LANGUAGE_CODE == 'ar' %} ml-auto{% else %} mr-auto{% endif %}">#}
{#    <li class="nav-item active">#}
{#        <a class="nav-link" href="{% url "home" %}">{% trans 'Home' %} <span class="sr-only">(current)</span></a>#}
{#    </li>#}
{#</ul>#}
<ul class="navbar-nav{% if LANGUAGE_CODE == 'ar' %} mr-auto{% else %} ml-auto{% endif %}">
    {% if user.is_authenticated %}
        <li class="nav-item dropdown d-none d-md-block">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"
               data-toggle="tooltip" data-placement="bottom" title="{{ user.get_full_name }}"><i
                    class="fas fa-user"></i>
                {% if request.user_agent.is_mobile %}
                    {{ user.get_full_name|truncatechars:30 }}
                {% else %}
                    {{ user.get_full_name|truncatechars:15 }}
                {% endif %}
            </a>
            <div class="dropdown-menu text-justify" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'user:profile' %}">
                    <i class="fas fa-user"></i>&nbsp;
                    {% trans "Profile" %}
                </a>
                <a class="dropdown-item" href="{% url 'user:user_logout' %}">
                    <i class="fas fa-sign-out-alt"></i>&nbsp;
                    {% trans "Logout" %}
                </a>
            </div>
        </li>
    {% else %}

        <li class="nav-item">
            <a class="nav-link" href="{% url 'user:user_login' %}">{% trans "Login" %}</a>
        </li>

    {% endif %}

    <li class="nav-item d-none d-md-block">
        <a class="nav-link" href="#"><span>|</span></a>
    </li>
    <li class="nav-item">
        <form id="lang-form" action="{% url 'set_language' %}" method="POST">{% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}"/>
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                {% if language.code != LANGUAGE_CODE %}
                    <input name="language" type="hidden" value="{{ language.code }}"/>
                    <a href="#" class="language-switcher nav-link"><span
                            class="lang-switch">{{ language.name_local }}</span></a>
                {% endif %}
            {% endfor %}
        </form>
    </li>
</ul>

main/templates/layout/tools/slidebar.html
{% load staticfiles %}
{% load i18n %}
<div off-canvas="menu-slidebar {% if LANGUAGE_CODE == 'en' %}left{% else %}right{% endif %} shift">
    <ul class="menu-slidebar-list">
        {% if user.is_authenticated %}
            <li class="menu-slidebar-item">
                <a class="nav-link" href="{% url 'home' %}">
                    <i class="fas fa-home fa-1x"></i>
                    {% trans "Home" %}
                </a>
            </li>
            <li class="menu-slidebar-item">
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    {% if language.code != LANGUAGE_CODE %}
                        <a href="#" class="language-switcher nav-link">
                            <i class="fa fa-globe " aria-hidden="true"></i>
                            <span class="lang-switch">{{ language.name_local }}</span></a>
                    {% endif %}
                {% endfor %}
            </li>
            <li class="menu-slidebar-item ">
                <a class="nav-link" href="{% url 'user:profile' %}">
                    <i class="fas fa-user fa-1x"></i>
                    {% trans "Profile" %}
                </a>
            </li>
            <li class="menu-slidebar-item">
                <a class="nav-link" href="{% url 'user:user_logout' %}">
                    <i class="fas fa-sign-out-alt"></i>
                    {% trans "Logout" %}
                </a>
            </li>
        {% else %}
            <li class="menu-slidebar-item">
                <a class="nav-link" href="{% url 'home' %}">
                    <i class="fas fa-home fa-1x"></i>
                    {% trans "Home" %}
                </a>
            </li>
            <li class="menu-slidebar-item">
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    {% if language.code != LANGUAGE_CODE %}
                        <a href="#" class="language-switcher nav-link">
                            <i class="fa fa-globe " aria-hidden="true"></i>
                            <span class="lang-switch">{{ language.name_local }}</span></a>
                    {% endif %}
                {% endfor %}
            </li>
            <li class="menu-slidebar-item">
                <a class="nav-link" href="{% url 'user:profile' %}">
                    <i class="fas fa-user fa-1x"></i>
                    {% trans "Profile" %}
                </a>
            </li>
            <li class="menu-slidebar-item">
                <a class="nav-link" href="{% url 'user:user_login' %}">
                    <i class="fas fa-sign-in-alt"></i>
                    {% trans "Login" %}
                </a>
            </li>
        {% endif %}
    </ul>
</div>